spring:
  data:
    mongodb:
      host: host.docker.internal
      database: pizzaorder
      port: 27017

# spring - mongodb database conncetion credentials. Set host "localhost" for local db connection